### ISSUE TITLE
Dependabot  glob-parent 보안 이슈

### ISSUE THREAD

**Issue by imki123** [bootpay/bootpay_js#10]
Github Dependabot에서 아래 보안 이슈를 발견했습니다. babel-cli 디펜던시 업데이트 부탁드립니다.

# glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex
- This affects the package glob-parent before 5.1.2. The enclosure regex used to check for strings ending in enclosure containing path separator.
- 디펜던시: glob-parent@^2.0.0 <- chokidar@^1.6.1(1.7.0) <- babel-cli@^6.26.0 <- bootpay-js@^3.3.3

**Comment by bootpay** [comment]
레포팅 감사드립니다. 오늘 중에 babel-cli 패치 버전으로 배포하도록 하겠습니다.

**Comment by bootpay** [comment]
babel-cli 패키지 의존성을 삭제한 버전이 3.3.6에 배포되었습니다. 예전에는 cli 패키지를 썼었으나 새로운 버전에서 저희가 의존성을 삭제하지 않아 legacy로 남아 있었던 부분입니다.

다른 궁금하신 점 있으시면 부트페이 관리자 https://admin.bootpay.co.kr 접속 후 오른 쪽 하단 채널톡으로 의견 남겨주세요 감사합니다.

**Comment by bootpay** [comment]
해당 이슈는 해결되었으로 저희가 닫도록 하겠습니다. 감사합니다!

**Comment by imki123** [comment]
@bootpay 확인 감사합니다.
