### ISSUE TITLE
본인인증 완료 후 페이지 스택이 하나 추가됩니다.

### ISSUE THREAD

**Issue by imki123** [bootpay/bootpay_js#12]
안녕하세요. 부트페이 v1을 사용하고 있습니다.
인증을 완료하고나면 예상치 않게 페이지 스택이 하나 추가되는데 문제를 해결하고 싶습니다.
아래 `배경` 처리된 부분이 의도치 않은 페이지로 보입니다.

개발환경
- react: 16.14.0
- react-router: 5.2.1
- bootpay-js: 3.3.6

### 예시1 (replace)
아래 예상처럼 페이지 스택을 2개로 관리하고 싶은데요. 본인인증을 완료하면 페이지 스택이 3개로 변경됩니다.
- 예상: A페이지 -> 부트페이 페이지(인증 완료 후 완료페이지로 replace)
- 실제: A페이지 -> 부트페이 페이지(인증 완료 후 완료페이지로 replace) -> `완료페이지`
  - 1스택: A페이지, 2스택: 완료페이지(3스택이 복사된것 처럼 작동), 3스택: `완료페이지`

### 예시2 (push)
인증 완료 시 replace를 사용하지 않고 push를 사용하면 3개 스택이 아닌 4개 스택이 됩니다.
- 예상: A페이지 -> 부트페이 페이지(인증 완료 후 완료페이지로 push) -> 완료페이지
- 실제: A페이지 -> 부트페이 페이지(인증 완료 후 완료페이지로 push) -> `부트페이 페이지` -> 완료페이지
  - 1스택: A페이지, 2스택: 부트페이 페이지(3스택이 복사된것 처럼 작동), 3스택: `부트페이 페이지`, 4스택: 완료페이지

3스택에서 의도치 않은 페이지가 추가되고 있습니다. 확인 부탁드립니다. 감사합니다.

**Comment by bootpay** [comment]
안녕하세요. 

history stack관련해서는 저희가 v1 버전은 당장 개선이 어려운 상태입니다. 다만 말씀하신 증상은 본인인증이 완료된 상태에서의 history stack의 문제인데 이 부분은 뭔가 잘못 진행이 되고 있거나 혹은 저희쪽의 버그로 보여지는 부분입니다.

v1의 경우엔 

1. js로 요청
2. api.bootpay.co.kr 로 잠시 이동 후
3. app.bootpay.co.kr로 이동
4. api.bootpay.co.kr로 돌아온 이후
5. 다날 본인인증 페이지로 진입
6. 다날 본인인증 완료 후 api.bootpay.co.kr 
7. SDK로 본인인증 완료 정보를 postMessage로 전송

이런 구조로 동작하게 됩니다.

위 일련의 과정중 3->4을 제외하고는 모두 POST로 이동하게 됩니다.
보통 SDK결제 완료 이벤트를 받으면 본인인증창에서 iFrame이 종료 되는 것이 정상입니다. 
그래서 실제로는 본인인증 완료가 되었고 내부적으로 onDone 이벤트를 받은 상태라면 뒤로가기를 누르시면 구성하신 사이트 페이지에서 뒤로가기가 진행됩니다.

말씀하시는 부분에서 저희가 의문이 드는 부분이

완료페이지에서 뒤로가기를 누르셨을때 부트페이로 돌아간다는 것으로 보이는데, SDK를 통해 onDone이벤트를 받은 상태고 iFrame 혹은 팝업이 제거된 상태라면 뒤로 돌아가면 안되는 구조입니다.

이 부분은 JS SDK이슈가 아니라서 여기에서 더 안내드리기는 어렵습니다.

https://admin.bootpay.co.kr 로 접속 하신 후 오른쪽 하단 채널톡으로 
말씀하신 일련의 과정을 담은 녹화본을 첨부해주시면 관련해서 증상을 확인하고 나서 더 자세히 안내드리도록 하겠습니다.

**Comment by imki123** [comment]
@bootpay 답변 감사합니다. 다른 방법으로 우회해볼까 했는데 좋은 해결책을 못찾아서 채널톡으로 녹화본 첨부하도록 하겠습니다.

**Comment by imki123** [comment]
관리자 페이지에 파일 첨부했습니다. 감사합니다.
