### ISSUE TITLE
가상계좌 환불 서비스는 없나요?

### ISSUE THREAD

**Issue by byungjuJin** [bootpay/bootpay_js#4]
iamport는 아래와 같은 서비스가 있습니다.  
[https://docs.iamport.kr/implementation/cancel#param-vbank](https://docs.iamport.kr/implementation/cancel#param-vbank)  
  
개발 중이거나 개발예정이면 일정을 알려주시면 감사하겠습니다.

**Comment by gosomi151101** [comment]
가상계좌 환불이 가능한 PG는 다날, 이니시스, KCP가 가능합니다. PG계약시에 CMS이체 환불 계약이 되어야하는데, 부트페이에서는 기본적으로 해당 기능이 계정별로 비활성화되어 있습니다.

몇가지 이유로 비활성화 되어 있는데

1. CMS이체 환불시 환불 계좌 확인이 불가능합니다. 계좌가 올바르지 않더라도 환불 처리 됩니다,
2. 환불시 건당 이체 비용이 발생합니다. 

이 3가지 PG를 사용하시면 필요하신 경우 활성화해드리고 있으며, 업무상 실수할 가능성이 높아서 가상계좌 환불은 직접 이체 환불을 추천드리고 있습니다.
