### ISSUE TITLE
typescript module support 문의

### ISSUE THREAD

**Issue by j1i-ian** [bootpay/bootpay_js#5]
안녕하세요 저희 프로젝트가 타입스크립트를 주로 이용 중인데 혹시 typescript 를 위한 d.ts module file 을 지원할 계획도 있을까요?

**Comment by qcoin-project** [comment]
안녕하세요. 부트페이입니다.
문의 남겨주셔서 감사합니다.

올해 안으로는 d.ts module를 따로 지원할 예정은 없습니다만, 내부 논의를 통해 지원 여부를 좀 더 넓혀보도록 하겠습니다.

좋은 제안주셔서 감사합니다.

**Comment by gosomi151101** [comment]
안녕하세요. 부트페이입니다.
문의남겨주셔서 감사합니다.

아직 d.ts module 지원 관련 논의가 없었습니다만 내부 회의를 통해 내년 상반기 중에 지원이 될 수 있도록 하겠습니다.

좋은 제안 감사드립니다.

**Comment by byungjuJin** [comment]
good! 곧 업데이트 되겠죠?

**Comment by pparkse2670** [comment]
해당 기능을 개발하시던 개발자분이 퇴사하셔서 진행이 어려울듯합니다.

**Comment by bootpay** [comment]
typescript는 v2 SDK로 지원됩니다. 
https://docs.bootpay.co.kr 에서 참고 부탁드립니다.
