### ISSUE TITLE
ReactNative에서 웹뷰를 이용한 결제를 구성하려는데 막히는 부분이 있습니다.

### ISSUE THREAD

**Issue by kimjoongwon** [bootpay/bootpay_js#6]
BootPay.request에서 request가 undefined가 뜨는 것을 확인 했는데 혹시 이유를 아시나요?

**Comment by Benjamin-Kang** [comment]
저희 채널덱으로 문의주신 내용인듯 합니다. 채널덱으로 답변드렸습니다. 감사합니다.
