### ISSUE TITLE
카카오페이 관련 API 수정 요청

### ISSUE THREAD

**Issue by paukparl** [bootpay/bootpay_js#8]
카카오페이 전용 결제창을 띄우기 위해 BootPay.request 함수의 method 파라미터에
documentation에 나온대로 "easy"를 넣었을때 작동하지 않습니다.
그 대신 "kakao"를 넣었을때 정상 작동 확인했습니다.

관련하여 README.md 수정 요청드립니다.

**Comment by Benjamin-Kang** [comment]
카카오페이가 두 종류가 있습니다.

1. 직가맹한 카카오페이
2. PG를 가맹을 통한 카카오페이


1번의 경우에 pg: kakao, method: easy 가 가능합니다만,
2번의 경우엔 pg: [pg alias], method: kakao로 가능합니다.

( 위 내용은 문서상에도 분리가 되어 있습니다. )

현재 이런 혼란을 줄이기 위해 몇몇 정리 작업을 하고 있습니다. 관련해서 업데이트가 되면 부트페이 관리자 공지를 통해 안내드리도록 하겠습니다.

피드백 주셔서 감사합니다.

**Comment by bootpay** [comment]
해당 이슈는 해결 된 것으로 닫도록 하겠습니다. 감사합니다.
