### ISSUE TITLE
typescript d.ts 지원 문의

### ISSUE THREAD

**Issue by KimPinot** [bootpay/bootpay_js#9]
안녕하세요. 저희 프로젝트가 타입스크립트를 주로 사용하다보니 d.ts 모듈의 지원이 필요한 사항입니다.
마지막 typescript 이슈에서는 담당하시는 개발자분이 퇴사하셨다는 내용을 끝으로 업데이트가 없는데, 아직도 지원 계획이 없는지 궁금합니다.

**Comment by bootpay** [comment]
typescript는 v2 SDK로 지원됩니다. 
https://docs.bootpay.co.kr 에서 참고 부탁드립니다.
